// <auto-generated />
using System;
using BourbonAe.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BourbonAe.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BourbonAe.Core.Data.Entities.Aesj1110Entity", b =>
                {
                    b.Property<string>("SlipNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SLIP_NO");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CUSTOMER_CD");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CUSTOMER_NM");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("SLIP_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("SlipNo");

                    b.ToTable("AESJ1110", (string)null);
                });

            modelBuilder.Entity("BourbonAe.Core.Models.Entities.Tokui", b =>
                {
                    b.Property<string>("TokuiCd")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KY_TOKUI_CD");

                    b.Property<string>("TokuiKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TOKUI_KANA");

                    b.Property<string>("TokuiNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TOKUI_NM");

                    b.HasKey("TokuiCd");

                    b.ToTable("M_TOKUI", (string)null);
                });

            modelBuilder.Entity("BourbonAe.Core.Services.Auth.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
